CREATE TABLE `ffe_list` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`category` varchar(100) NOT NULL,
	`type` varchar(100),
	`quantity` int NOT NULL,
	`unit` varchar(50) DEFAULT 'piece',
	`estimatedUnitCost` decimal(10,2),
	`totalEstimatedCost` decimal(15,2),
	`manufacturer` varchar(255),
	`modelNumber` varchar(100),
	`specificationNotes` text,
	`installationNotes` text,
	`requiredDate` timestamp,
	`status` enum('pending','ordered','delivered','installed','cancelled') NOT NULL DEFAULT 'pending',
	`priority` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`linkedProcurementItemId` int,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ffe_list_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `material_list` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`category` varchar(100) NOT NULL,
	`quantity` decimal(10,2) NOT NULL,
	`unit` varchar(50) NOT NULL,
	`estimatedUnitCost` decimal(10,2),
	`totalEstimatedCost` decimal(15,2),
	`supplier` varchar(255),
	`specificationNotes` text,
	`requiredDate` timestamp,
	`status` enum('pending','ordered','delivered','used','cancelled') NOT NULL DEFAULT 'pending',
	`priority` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`linkedProcurementItemId` int,
	`createdById` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `material_list_id` PRIMARY KEY(`id`)
);
