/**
 * Email Templates with AliPM Branding
 * Professional email templates for automated reports and notifications
 */

export interface EmailTemplate {
  subject: string;
  html: string;
  text: string;
}

const BRAND_COLOR = "#0B1E3D"; // Navy blue
const ACCENT_COLOR = "#D4AF37"; // Gold
const COMPANY_NAME = "AliPM";
const COMPANY_TAGLINE = "Fit-Out Project Management";

/**
 * Email header with AliPM branding
 */
function getEmailHeader(): string {
  return `
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: ${BRAND_COLOR}; padding: 20px 0;">
      <tr>
        <td style="text-align: center; padding: 20px;">
          <h1 style="color: ${ACCENT_COLOR}; font-size: 28px; margin: 0; font-weight: bold;">
            ${COMPANY_NAME}
          </h1>
          <p style="color: #ffffff; font-size: 14px; margin: 5px 0 0 0;">
            ${COMPANY_TAGLINE}
          </p>
        </td>
      </tr>
    </table>
  `;
}

/**
 * Email footer with AliPM contact info
 */
function getEmailFooter(): string {
  return `
    <table width="100%" cellpadding="0" cellspacing="0" style="background-color: #f5f5f5; border-top: 2px solid ${ACCENT_COLOR}; margin-top: 30px; padding: 20px 0;">
      <tr>
        <td style="text-align: center; padding: 20px; color: #666; font-size: 12px;">
          <p style="margin: 0;">
            <strong>${COMPANY_NAME} - ${COMPANY_TAGLINE}</strong>
          </p>
          <p style="margin: 5px 0 0 0;">
            © ${new Date().getFullYear()} ${COMPANY_NAME}. All rights reserved.
          </p>
          <p style="margin: 10px 0 0 0; color: #999;">
            This is an automated message. Please do not reply to this email.
          </p>
        </td>
      </tr>
    </table>
  `;
}

/**
 * Weekly report email template
 */
export function getWeeklyReportEmailTemplate(
  projectName: string,
  reportContent: string,
  viewLink: string
): EmailTemplate {
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; }
          .content { padding: 20px; }
          .section { margin: 20px 0; padding: 15px; border-left: 4px solid ${ACCENT_COLOR}; background-color: #f9f9f9; }
          .section-title { color: ${BRAND_COLOR}; font-size: 16px; font-weight: bold; margin: 0 0 10px 0; }
          .cta-button { display: inline-block; background-color: ${ACCENT_COLOR}; color: ${BRAND_COLOR}; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-weight: bold; margin-top: 10px; }
          .metric { display: inline-block; margin-right: 20px; margin-bottom: 10px; }
          .metric-value { color: ${ACCENT_COLOR}; font-size: 24px; font-weight: bold; }
          .metric-label { color: #666; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="container">
          ${getEmailHeader()}
          
          <div class="content">
            <p>Hello,</p>
            
            <p>Your weekly project report for <strong>${projectName}</strong> is ready.</p>
            
            <div class="section">
              <div class="section-title">📊 Project Status</div>
              ${reportContent}
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
              <a href="${viewLink}" class="cta-button">View Full Report</a>
            </div>
            
            <p style="color: #999; font-size: 12px;">
              This report was automatically generated by ${COMPANY_NAME}. 
              For questions or concerns, please contact your project manager.
            </p>
          </div>
          
          ${getEmailFooter()}
        </div>
      </body>
    </html>
  `;

  const text = `
${COMPANY_NAME} - ${COMPANY_TAGLINE}

Weekly Project Report: ${projectName}

${reportContent}

View Full Report: ${viewLink}

---
This report was automatically generated by ${COMPANY_NAME}.
© ${new Date().getFullYear()} ${COMPANY_NAME}. All rights reserved.
  `;

  return {
    subject: `${COMPANY_NAME}: Weekly Report - ${projectName}`,
    html,
    text,
  };
}

/**
 * Document generation notification email template
 */
export function getDocumentGenerationEmailTemplate(
  documentType: string,
  projectName: string,
  downloadLink: string
): EmailTemplate {
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; }
          .content { padding: 20px; }
          .success-box { background-color: #f0f9ff; border-left: 4px solid #10b981; padding: 15px; margin: 20px 0; }
          .success-icon { color: #10b981; font-size: 24px; margin-right: 10px; }
          .cta-button { display: inline-block; background-color: ${ACCENT_COLOR}; color: ${BRAND_COLOR}; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-weight: bold; margin-top: 10px; }
        </style>
      </head>
      <body>
        <div class="container">
          ${getEmailHeader()}
          
          <div class="content">
            <p>Hello,</p>
            
            <div class="success-box">
              <span class="success-icon">✓</span>
              <strong>Document Generated Successfully!</strong>
            </div>
            
            <p>Your <strong>${documentType}</strong> for project <strong>${projectName}</strong> has been generated and is ready for download.</p>
            
            <div style="text-align: center; margin: 30px 0;">
              <a href="${downloadLink}" class="cta-button">Download Document</a>
            </div>
            
            <p style="color: #999; font-size: 12px;">
              This document was generated by ${COMPANY_NAME} and contains professional project documentation.
            </p>
          </div>
          
          ${getEmailFooter()}
        </div>
      </body>
    </html>
  `;

  const text = `
${COMPANY_NAME} - ${COMPANY_TAGLINE}

Document Generated: ${documentType}

Your ${documentType} for project ${projectName} has been generated successfully.

Download: ${downloadLink}

---
© ${new Date().getFullYear()} ${COMPANY_NAME}. All rights reserved.
  `;

  return {
    subject: `${COMPANY_NAME}: ${documentType} Ready - ${projectName}`,
    html,
    text,
  };
}

/**
 * Task assignment notification email template
 */
export function getTaskAssignmentEmailTemplate(
  taskName: string,
  projectName: string,
  assignedBy: string,
  dueDate: string,
  taskLink: string
): EmailTemplate {
  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; }
          .content { padding: 20px; }
          .task-box { background-color: #fafafa; border-left: 4px solid ${ACCENT_COLOR}; padding: 15px; margin: 20px 0; }
          .task-detail { margin: 8px 0; }
          .task-label { color: #666; font-size: 12px; text-transform: uppercase; }
          .task-value { color: ${BRAND_COLOR}; font-weight: bold; }
          .cta-button { display: inline-block; background-color: ${ACCENT_COLOR}; color: ${BRAND_COLOR}; padding: 12px 24px; text-decoration: none; border-radius: 4px; font-weight: bold; margin-top: 10px; }
        </style>
      </head>
      <body>
        <div class="container">
          ${getEmailHeader()}
          
          <div class="content">
            <p>Hello,</p>
            
            <p>You have been assigned a new task in <strong>${projectName}</strong>.</p>
            
            <div class="task-box">
              <div class="task-detail">
                <div class="task-label">Task</div>
                <div class="task-value">${taskName}</div>
              </div>
              <div class="task-detail">
                <div class="task-label">Project</div>
                <div class="task-value">${projectName}</div>
              </div>
              <div class="task-detail">
                <div class="task-label">Assigned By</div>
                <div class="task-value">${assignedBy}</div>
              </div>
              <div class="task-detail">
                <div class="task-label">Due Date</div>
                <div class="task-value">${dueDate}</div>
              </div>
            </div>
            
            <div style="text-align: center; margin: 30px 0;">
              <a href="${taskLink}" class="cta-button">View Task Details</a>
            </div>
          </div>
          
          ${getEmailFooter()}
        </div>
      </body>
    </html>
  `;

  const text = `
${COMPANY_NAME} - ${COMPANY_TAGLINE}

New Task Assignment

Task: ${taskName}
Project: ${projectName}
Assigned By: ${assignedBy}
Due Date: ${dueDate}

View Task: ${taskLink}

---
© ${new Date().getFullYear()} ${COMPANY_NAME}. All rights reserved.
  `;

  return {
    subject: `${COMPANY_NAME}: New Task Assigned - ${taskName}`,
    html,
    text,
  };
}
